In [15]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print (a) # It is ndarray thus ',' not present in between number

<class 'numpy.ndarray'>
[1 2 3]


CREATE DYNAMIC NUMPY ARRAY 

In [20]:
a = np.arange(10,20) 
print(a)

[10 11 12 13 14 15 16 17 18 19]


CREATE DYNAMIC NUMPY ARRAY WITH ZERO AND RESHAPE THE NUMPY ARRAY USING RESHAPE AND RAVEL [CONVERT ONE DIMENSION ARRAY]

In [42]:
a = np.zeros((2,3)) # (2,3) means two rows and three column
print(a)
b= np.zeros(9)
print(b)
c = b.reshape(3,3)
print('Reshape b',c)# reshape the array
d = c.reshape(9)
print(d)
e=a.ravel() 
print(e)
#Example of ravel
arr = np.array([[1,2,3],[1,8,6]])
print(arr)
print(arr.ravel())


[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
Reshape b [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[[1 2 3]
 [1 8 6]]
[1 2 3 1 8 6]


CREATE N NUMBER OF BIN BETWEEN TWO NUMBERS:- np.linspace(startnum,endnum,bin size) 

In [26]:
print(np.linspace(1,20,5)) 

[ 1.    5.75 10.5  15.25 20.  ]


NUMPY DATATYPE

In [48]:
#dtype = int32
b = np.array([[1,2,3],[5,6,7],[7,8,9]])
print(type(b))
print(b.dtype)

#dtype = <U11 => All the elements got converted into a string.
b= np.array([[1,2,3],[4,'tt',6]])
print(b.dtype)

#dtype = int32
b= np.array([[1,2,3],[4,True,6]])
print(b.dtype)

#dtype = <U11 => All the elements got converted into a string.
b= np.array([[1,2,3],[4,True,'tt']])
print(b.dtype)

#dtype = <U11 => All the elements got converted into a string.
b= np.array([[1,'2','tt'],[4,True,'tt']])
print(b.dtype)

<class 'numpy.ndarray'>
int32
<U11
int32
<U11
<U11


ADDITION,SUBTRACTION, MULTIPLICATION AND DIVITION if dtype is int32

In [61]:
b = np.array([[1,2,3],[5,6,7],[7,8,9]])
c = np.array([[8,1,1],[5,6,9],[1,2,2]])
print('Addition:',b+c)
print('Subtraction:',b-c)
print('Multiplication:',b*c)
print('Divition:',b/c)


Addition: [[ 9  3  4]
 [10 12 16]
 [ 8 10 11]]
Subtraction: [[-7  1  2]
 [ 0  0 -2]
 [ 6  6  7]]
Multiplication: [[ 8  2  3]
 [25 36 63]
 [ 7 16 18]]
Divition: [[0.125      2.         3.        ]
 [1.         1.         0.77777778]
 [7.         4.         4.5       ]]


NUMPY SUBSETTING

In [78]:
b = np.array([[1,2,3],[5,6,7],[7,8,9]])
print(b[1])
print(b[-1])
print(b[::-1]) # Reverse the array 
print(b[b>3]) # Outputs only those elements as another numpy array which are greater than 3 - [5 6 7 7 8 9]

x = np.array([1,2,3,4,5])
y = x>3
z=[2,4]
print(y) #[False False False  True  True]
print(x[y]) # [4 5]
print(x[z]) # z act as index value so the outcome [3 5] beacuse x[2] =3 and x[4] =5 i.e. start index with 0

[5 6 7]
[7 8 9]
[[7 8 9]
 [5 6 7]
 [1 2 3]]
[5 6 7 7 8 9]
[False False False  True  True]
[4 5]
[3 5]


SLICING

In [86]:
b = np.array([[[1,2,3],[5,6,7],[7,8,9]],
             [[5,6,3],[5,6,7],[2,3,9]]])

print(b)
print(b[1,1,1]+7) # b[1,1,1] = 6 so 6+7 =13

b = b.ravel()
print(b)

arr_slice = slice(2,5,6)
print(arr_slice)

print(b[arr_slice])

[[[1 2 3]
  [5 6 7]
  [7 8 9]]

 [[5 6 3]
  [5 6 7]
  [2 3 9]]]
13
[1 2 3 5 6 7 7 8 9 5 6 3 5 6 7 2 3 9]
slice(2, 5, 6)
[3]


In [89]:
c= np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[9,8,7],[8,4,4],[3,2,1]],
    [[7,8,9],[1,4,3],[4,5,6]]
])

print(c)
d=c[1,1,1]
print(d+7)

c=c.ravel()
print(c)
arr_slice = slice(10,20,3)
element = c[11]
print('arr_slice:-',arr_slice)
print('c[arr_slice]:-',c[arr_slice])
print(c[15:])
#print(c[0:1,0:1,0:1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [8 4 4]
  [3 2 1]]

 [[7 8 9]
  [1 4 3]
  [4 5 6]]]
11
[1 2 3 4 5 6 7 8 9 9 8 7 8 4 4 3 2 1 7 8 9 1 4 3 4 5 6]
arr_slice:- slice(10, 20, 3)
c[arr_slice]:- [8 4 2 8]
[3 2 1 7 8 9 1 4 3 4 5 6]


CREATE EMPTY ARRAY AND USE OF ndim, size and shape

In [100]:
c = np.empty([5,2],dtype=int)
print(c)
print(c.shape)
print(c.ndim)
print(c.size)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
(5, 2)
2
10
